name: flutter_businesscard
description: Business Card application.
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - images/johan.jpg

  fonts:
    - family: Pacifico
      fonts:
      - asset: fonts/Pacifico-Regular.ttf

    - family: Source Sans Pro
      fonts:
      - asset: fonts/SourceSansPro-Regular.ttf
